// Home

// Quran
export const SET_IS_SURAS_LIST_LOADING = "SET_IS_SURAS_LIST_LOADING";
export const SET_IS_SURA_DETAILS_LOADING = "SET_IS_SURA_DETAILS_LOADING";
export const SET_IS_SURA_TELAWA_LOADING = "SET_IS_SURA_TELAWA_LOADING";
export const SET_IS_SURA_VIDEO_TAFSIR_LOADING =
  "SET_IS_SURA_VIDEO_TAFSIR_LOADING";
export const SET_IS_SURA_AUDIO_TAFSIR_LOADING =
  "SET_IS_SURA_AUDIO_TAFSIR_LOADING";
// export const SET_IS_SURA_TEXT_TAFSIR_LOADING = 'SET_IS_SURA_TEXT_TAFSIR_LOADING';
export const SET_SURAS_LIST = "SET_SURAS_LIST";
export const SET_SURA = "SET_SURA";
export const SET_SURA_AUDIO_LIST = "SET_SURA_AUDIO_LIST";
export const SET_SURA_AUDIO_TAFSIR_LIST = "SET_SURA_AUDIO_TAFSIR_LIST";
export const SET_SURA_VIDEO_TAFSIR_LIST = "SET_SURA_VIDEO_TAFSIR_LIST";

// Hadith
export const SET_IS_HADITH_BOOKS_LIST_LOADING =
  "SET_IS_HADITH_BOOKS_LIST_LOADING";
export const SET_IS_HADITH_BOOK_CHAPTERS_LIST_LOADING =
  "SET_IS_HADITH_BOOK_CHAPTERS_LIST_LOADING";
export const SET_IS_HADITH_LIST_LOADING = "SET_IS_HADITH_LIST_LOADING";
export const SET_IS_HADITH_DETAILS_LOADING = "SET_IS_HADITH_DETAILS_LOADING";
export const SET_HADITH_BOOKS_LIST = "SET_HADITH_BOOKS_LIST";
export const SET_HADITH_BOOK_CHAPTERS_LIST = "SET_HADITH_BOOK_CHAPTERS_LIST";
export const SET_HADITH_LIST = "SET_HADITH_LIST";
export const SET_HADITH = "SET_HADITH";
export const SET_HADITH_TAFSIR = "SET_HADITH_TAFSIR";

// Other Science
export const SET_IS_OTHER_SCIENCE_LOADING = "SET_IS_OTHER_SCIENCE_LOADING";
export const SET_IS_OTHER_SCIENCE_AUDIO_LOADING =
  "SET_IS_OTHER_SCIENCE_AUDIO_LOADING";
export const SET_IS_OTHER_SCIENCE_VIDEO_LOADING =
  "SET_IS_OTHER_SCIENCE_VIDEO_LOADING";
export const SET_OTHER_SCIENCE_AUDIO_LIST = "SET_OTHER_SCIENCE_AUDIO_LIST";
export const SET_OTHER_SCIENCE_VIDEO_LIST = "SET_OTHER_SCIENCE_VIDEO_LIST";
export const SET_OTHER_SCIENCE_AUDIO_SUBJECTS =
  "SET_OTHER_SCIENCE_AUDIO_SUBJECTS";
export const SET_OTHER_SCIENCE_VIDEO_SUBJECTS =
  "SET_OTHER_SCIENCE_VIDEO_SUBJECTS";

// Fatwas
export const SET_IS_FATWAS_LIST_LOADING = "SET_IS_FATWAS_LIST_LOADING";
export const SET_FATWAS_LIST = "SET_FATWAS_LIST";

// Books
export const SET_IS_BOOKS_LOADING = "SET_IS_BOOKS_LOADING";
export const SET_IS_BOOK_DETAILS_LOADING = "SET_IS_BOOK_DETAILS_LOADING";
export const SET_BOOKS = "SET_BOOKS";

// Articles
export const SET_IS_ARTICLES_LOADING = "SET_IS_ARTICLES_LOADING";
export const SET_IS_ARTICLE_DETAILS_LOADING = "SET_IS_ARTICLE_DETAILS_LOADING";
export const SET_ARTICLES = "SET_ARTICLES";

// Sessions
export const SET_IS_SESSIONS_LOADING = "SET_IS_SESSIONS_LOADING";
export const SET_IS_SESSION_VIDEO_LOADING = "SET_IS_SESSION_VIDEO_LOADING";
export const SET_SESSIONS = "SET_SESSIONS";
export const SET_SESSION = "SET_SESSION";

// Favorites
export const SET_IS_FAVORITES_LOADING = "SET_IS_FAVORITES_LOADING";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";

// Call Us
export const SET_IS_CALL_US_LOADING = "SET_IS_CALL_US_LOADING";
export const SET_CALL_US_PHONE_NUMBERS = "SET_CALL_US_PHONE_NUMBERS";

export const SEARCH_LOADING = "SEARCH_LOADING";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
